name: Release on push on main branch

on:
  push:
    branches:
      - feature/release-workflow #temporary, switch to main

jobs:
  release-snek:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Node dependencies
        run: npm install

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Install .Net dependencies
        run: dotnet restore ./Snek

      - name: Run build
        run: dotnet build ./Snek

      - name: Fetch release version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches "feature/release-workflow" --dry-run && echo "stuff about releas version" $RELEASE_VERSION

      - name: Run publish
        run: dotnet publish -c release -r win-x64 ./Snek -p:Version=${{ env.RELEASE_VERSION }} -o Snek

      - name: ZIP my-project directory
        run: zip -r Snek.zip Snek

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches main
