name: Release on push on main branch

on:
  push:
    branches:
      - dev #temporary run on dev, will be changed to main in future

jobs:
  release-snek:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16.x

      - name: Install Node dependencies
        run: npm install

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Install .Net dependencies
        run: dotnet restore ./Snek

      - name: Run build
        run: dotnet build ./Snek

      - name: Fetch release version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches main --dry-run

      - name: Run publish
        run: dotnet publish -c release -r win-x64 ./SolutionDir -p:Version=${{ env.RELEASE_VERSION }} -o Snek_v${{ env.RELEASE_VERSION }}

      - name: ZIP my-project directory
        run: zip -r Snek_v${{ env.RELEASE_VERSION }}.zip Snek_v${{ env.RELEASE_VERSION }}

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches main
