name: Release Snek

on:
  push:
    branches:
      - main
      - dev

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    outputs:
      next-release-version: ${{steps.capture-next-version.outputs.NEXT_RELEASE_VERSION}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Node dependencies
        run: npm install

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Install .Net dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build

      - name: Test
        run: dotnet test

      - name: Fetch next version
        id: fetch-next-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          npx semantic-release --branches "dev" --dry-run

      - name: Capture next version
        id: capture-next-version
        run: echo "NEXT_RELEASE_VERSION=${{env.RELEASE_VERSION}}" >> $GITHUB_OUTPUT

  publish-and-release:
    needs: build-and-test
    runs-on: ubuntu-latest
    if: ${{needs.build-and-test.outputs.next-release-version}} != ''
    env:
      RELEASE_VERSION: ${{needs.build-and-test.outputs.next-release-version}}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 18.x

      - name: Install Node dependencies
        run: npm install

      - name: Setup .Net
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "7.0.x"

      - name: Run publish Windows
        run: dotnet publish -c release -r win-x64 ./Snek.Console "-p:Version=${{ env.RELEASE_VERSION }}" -o build/win-x64

      - name: ZIP Windows output
        run: cd build/win-x64 && zip -r ../Snek_win-x64.zip * && cd ../..

      - name: Run publish Linux
        run: dotnet publish -c release -r linux-x64 ./Snek.Console -p:Version=${{ env.RELEASE_VERSION }} -o build/linux-x64

      - name: ZIP Linux output
        run: cd build/linux-x64 && zip -r ../Snek_linux-x64.zip * && cd ../..

      - name: Run publish OSX
        run: dotnet publish -c release -r osx-x64 ./Snek.Console -p:Version=${{ env.RELEASE_VERSION }} -o build/osx-x64

      - name: ZIP OSX output
        run: cd build/osx-x64 && zip -r ../Snek_osx-x64.zip * && cd ../..

      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release --branches dev
